### ISSUE TITLE
Front-end frameworks - should we? which one?

### ISSUE THREAD

**Issue by ghedwards** [rickbergfalk/sqlpad#100]
Any thoughts on using Angular?

**Comment by rickbergfalk** [comment]
Hi @ghedwards. I was thinking about looking into Vue or React this summer. Any particular reason why Angular specifically?

**Comment by rickbergfalk** [comment]
I should add I'm open to discussion on front-end frameworks. 

Personally, I'm less inclined to go angular because of the whole v1/v2 incompatibility and react's surge in popularity. Vue.js seems to be the simpler of the 3 libraries... although I haven't actually tried them out yet. I've just been reading the docs.

Any input is welcome :)

**Comment by ghedwards** [comment]
React sounds good to me, a couple of things to think about / discuss
- Flux ?
- Flux framework ? ( alt.js, fluxxorm, fluxthis )
- ES6 / Babel ?

**Comment by rickbergfalk** [comment]
yeah that's the intimidating part about going with react... all those other decisions. I suppose that's one of the benefits of angular right in that all those choices are made for you? 

I think it'd be nice to get sqlpad up to speed with modern javascript development practices, but at the same time I'd like to be careful and not overly complicate things.

**Comment by ghedwards** [comment]
Built a "very early" prototype using React ("react-engine") as the view engine in my fork use "npm run react" to start the react version. [https://github.com/ghedwards/sqlpad/](https://github.com/ghedwards/sqlpad/)

**Comment by rickbergfalk** [comment]
Just to circle back on this issue - decided to gradually adopt react. See wiki for larger plan.
