### ISSUE TITLE
HA Storage

### ISSUE THREAD

**Issue by solomongifford** [rickbergfalk/sqlpad#101]
I love the idea of in memory persistent storage but it means the application cannot be run in an HA environment with multiple webheads.  Besides db.cache, the other dbs should really be able to be stored in an external database - has anyone done any work to support this?

**Comment by rickbergfalk** [comment]
Hi @solomongifford. There hasn't that I know of. What external database were you thinking of? Anything particular in mind?

I'm open to ideas as long as the core sqlpad installation remains simple.

**Comment by ghedwards** [comment]
Mongodb ?

**Comment by solomongifford** [comment]
Mongodb is the natural choice since it likely would mean the least amount of work; however, I'd prefer something like https://github.com/biggora/caminte so that the backend storage model is pluggable - we currently use mysql and cassandra for example.

**Comment by rickbergfalk** [comment]
One of the difficulties going down this route is everyone is going to have a different database backend preference. For relational databases, schema migrations would also need to be written, so that would need to be accommodated as well.

Something I wouldn't want to lose is the basic/standard installation simplicity. ```npm install sqlpad -g``` should always be enough to get started.

I haven't been able to find an orm that supports the currently used database [nedb.js](https://github.com/louischatriot/nedb/).

I wouldn't mind migrating to something like sqlite for the base install (the idea of being able to use SqlPad to query against its own database seems kinda fun, especially if SqlPad started to record usage statistics)

I have a long list of todo items for sqlpad currently, so I don't see myself taking this challenge on any time soon. I wouldn't be opposed to someone else taking it on, provided all the above things are also solved and considered...

**Comment by rickbergfalk** [comment]
After giving it some thought I've decided to keep sqlpad on an embedded database. I see the benefits of separating out the database but I think it'll add more complication than I would like to support for this project. 

On the upside, the next major release of SqlPad has all the database interactions separated out into models. It should be a lot easier to fork and port sqlpad to another backend as desired.
