### ISSUE TITLE
configstore locaton

### ISSUE THREAD

**Issue by glugy** [rickbergfalk/sqlpad#113]
Hello, I ran into some problems while getting sqlpad to run as a service on FreeBSD.  This may apply to other platforms as well.
sqlpad tries to create a ~/.config/configstore/update-notifier-sqlpad.json file when starting.  I was using the FreeBSD init system to daemonize sqlpad with an unprivledged system user. ("www" in my case which has no home directory).  The result was a .config folder at "/" and only root permissions.
While I was able to get things working with some permissions changes, it would be nice if the configstore either resided in the --dir location, or the configstore location could be specified with a command line switch.

Thanks!

**Comment by rickbergfalk** [comment]
Hi @glugy 

It looks like the issue stems from the update-notifier package used by sqlpad. Things have been fixed in the latest version of the module, so I'll update. 

Unfortunately there isn't a way to configure where that update-notifier file is kept.

I've been giving some thought to removing the command-line update notice to something in the web interface since that's where it would be seen anyways. I'm assuming SqlPad is mostly run as a service so its a very good chance that update notice isn't seen by a lot of its users.

**Comment by glugy** [comment]
For me, the command-line update notice was more trouble than it's worth, so I wouldn't be sad to see it go.  Thanks!
