### ISSUE TITLE
SQL Query - Typeahead feature

### ISSUE THREAD

**Issue by gamefundas** [rickbergfalk/sqlpad#123]
The last time I checked SqlPad didn't suggest completions for column names, reserved keywords etc through typeahead or suggestion mechanism on the editor pane. Is this something that's available now?

Its a very handy feature for my analyst team who prefer to use the completions to their advantage instead of typing keywords, columns etc in the query.

**Comment by rickbergfalk** [comment]
hi @gamefundas 

This is not available now but it'd definitely be something worth adding. I'd accept a pull request if someone wanted to take this on :)

**Comment by rickbergfalk** [comment]
An early first attempt at this is in the latest beta published to npm - it's quite limited right now... it doesn't handle table aliases or tables with spaces, and bracketed/quoted tables likely don't give expected behavior either, but its something...

To install the beta, run `npm install -g sqlpad@beta`
