### ISSUE TITLE
Version Control Git

### ISSUE THREAD

**Issue by sbansal6** [rickbergfalk/sqlpad#125]
Any plans to implement version control on schema's

**Comment by rickbergfalk** [comment]
Hi @sbansal6 - Not sure I understand. Are you talking about the database schema of the connection or of sqlpad's object model schemas?

**Comment by jameswinegar** [comment]
I think having VCS on the query could be nice and the ability to roll back to a previous version of your saved query.

**Comment by sbansal6** [comment]
@rickbergfalk :- I mean source controlling database schema and objects. Their no open source tool that does it, only few proprietary ones.

**Comment by sbansal6** [comment]
http://www.red-gate.com/products/sql-development/sql-source-control/

**Comment by rickbergfalk** [comment]
@sbansal6 - I've used red-gate's tooling in the past and their sql source control is really cool. Unfortunately though I think it might be a bit out of scope for this project...

@jameswinegar query history would be a nice add, although I think we'd need a way to limit it in some way. The embedded database used by sqlpad stores a copy of everything in memory. While I'm sure it could hold a lot, if such a feature was worked on there would need to be a way to limit the save history... maybe to the previous n versions (maybe even configurable in the settings?).

If that seems desirable we can repurpose this issue - otherwise I can close it.

**Comment by rickbergfalk** [comment]
I'm going to close this issue for now - open to any pr that adds query history/previous query versions.
