### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by jameswinegar** [rickbergfalk/sqlpad#126]
I've never written anything in Node so I was wondering if this is as easy to implement as I think. Would I just need to edit the `server.js` file such that if a key is in config or passed in environment then to require https and run that way?

**Comment by rickbergfalk** [comment]
I've never implemented https via express directly, but I have seen some code snippets, and I do believe its as easy as passing in the required config. (a quick google led me to this post http://blog.mgechev.com/2014/02/19/create-https-tls-ssl-application-with-express-nodejs/)

If you'd like to take this on as well, you would approach the config in a similar way you'd approach the config for the SMTP port, by defining a config item in [config-items.toml](https://github.com/rickbergfalk/sqlpad/blob/master/resources/config-items.toml)

Since this is used for creating the expressjs http server, you probably want to use interface = "env". And maybe 2 settings, one for key file path and another for cert file path? 

The few times I've set this up, I've use nginx in front of sqlpad, running sqlpad on an alternate port (like 3000) and then forwarding the a subdomain to the sqlpad port, with nginx handling the HTTPS piece. 

Definitely welcome a pull request if you get this figured out though! Feel free to reach out if you need anything.

**Comment by jameswinegar** [comment]
My use case requires both changes! So hopefully I can make them work tomorrow sometime. Read through the code base today to make sure I understood it. 

I want to make the http vs https robust enough so people don't have to create keys and blah if they don't need it.

**Comment by rickbergfalk** [comment]
Hi @jameswinegar - this was included in the v2.1.0 publish to npm. thanks! Hope you've enjoyed node so far :)
