### ISSUE TITLE
TypeError: Cannot read property 'table_type' of undefined

### ISSUE THREAD

**Issue by santoshsahoo** [rickbergfalk/sqlpad#131]
After migrating from 1x:

The object browser fails to load with error:

browserified.js:64 TypeError: Cannot read property 'table_type' of undefined(anonymous function) @ browserified.js:64

**Comment by rickbergfalk** [comment]
Hi @santoshsahoo - Could you try forcing a refresh on the schema browser by clicking the refresh icon? the object formatting behind the scene changed between v1 and v2, and I think your sqlpad instance might be picking up the cached schema (though I thought this was getting cleared between v1 and v2, so not sure what is going on here)

Let me know if that fixes your issue..

**Comment by vweevers** [comment]
I had the same issue. For some reason, the migration did not run at all (but no error was logged either, so I didn't find out this was the issue until later). Because of that, we lost the admin roles, and got the schema error described here. Only when we copied the old database again and manually removed the cache (`rm -rf db/cache db/cache.db`) before anything else, did the migration run.

**Comment by rickbergfalk** [comment]
I haven't had time to look too far into this, but I recall testing it a few times to ensure the migrations ran successfully.

The db migrations are run after the nedb database loads, but it doesn't prevent the rest of sqlpad from doing its thing, so I'm wondering if that could cause a problem...

Or maybe this is a permissions/OS/node version thing? I'd think an error would at least be logged if that were the case though.

**Comment by vweevers** [comment]
I can't replicate it anymore. My best guess is that the cache datastore was broken somehow, failed to load, and then the migrations didn't run because of the if-statement in [lib/db.js#L48](https://github.com/rickbergfalk/sqlpad/blob/b443628aa3c14828194852f2c36fd2fd712cdbf3/lib/db.js#L48):

```
if (db.loadedDbs.length === db.instances.length) {
      onAllDatabasesLoaded()
}
```

**Comment by vweevers** [comment]
Update: it might (also) be an issue with nodemon and npm's shell quoting. I noticed that a change to `db/schemaVersion.json` - which *should* be ignored - triggers a restart. This is problematic because this file changes in every step of the migration. So the next steps (as well as other stuff happening at the same time) might not get a chance to safely finish.

**Comment by vweevers** [comment]
To make the ignore patterns work cross-platform, we can place them in a `nodemon.json`:

```json
{
  "ignore": ["public/*", "client-js/*", "db/*"]
}
```

**Comment by vweevers** [comment]
Hm, with the above `nodemon.json`, nodemon does not watch *any* files. I also tried `nodemon --ignore ./db` (without a glob star), but this has no effect if the directory does not initially exist. I'm getting frustrated with nodemon, tbh. These are not just bugs, but fundamental design problems.

@rickbergfalk how do you feel about switching to [node-dev](https://github.com/fgnass/node-dev) instead? It doesn't need ignore patterns and works out of the box, cross-platform.

**Comment by vweevers** [comment]
FIY I'm working on a PR to enforce a strict order of database initialization (i.e. run migrations first, then add indexes, then the rest). If you're OK with `node-dev` then I'll include that in this PR.

**Comment by rickbergfalk** [comment]
Node-dev looks great! Totally okay with swapping it out. Feel free to
re-arrange things as you see fit :)

**Comment by rickbergfalk** [comment]
I'm pretty sure this issue is resolved with the restructuring of startup. v2 has been out a while too so hopefully there aren't v1s sitting out there unmigrated...
