### ISSUE TITLE
cancel queries or timeout option

### ISSUE THREAD

**Issue by raybuhr** [rickbergfalk/sqlpad#155]
If a user writes a query that is not efficient and abandons the sqlpad query page, it appears that the database will still attempt to complete the query behind the scenes. 

Can there be an option in **configuration** or **connection** to add a time out variable? Alternatively, a cancel query button on the query page? Or preferably, both.

**Comment by rickbergfalk** [comment]
Hi @raybuhr - I think a timeout config is something possible short-term. Eventually I'd like the ability to cancel queries as well, but that will require larger changes.

Any preference in whether timeouts are defined in configuration (for all connections) or at the connection level? 

I could almost see it going both places, for specific connections to override the main config setting... 

Thoughts?

**Comment by raybuhr** [comment]
I like that idea of having a global option in config and then an override option in the connection. Personally, I think having no timeout would be best for the distributed databases and a timeout of like 30 minutes on the traditional RDBMS connections.

**Comment by Shadow00Caster** [comment]
@rickbergfalk Is this something that is working?  On version 3.1.0 I have confirmed that SQLPad times out at 2 minutes even with remote execution on MSSQL set to 10 minutes.  I am running as a Docker container.

**Comment by rickbergfalk** [comment]
This issue is closed in that the http timeout of 2 minutes is now configurable. What isn't addressed is that queries will keep on running in background. Fixing that requires special handling for each db driver in node unfortunately (there's no common JDBC/ODBC driver that standardizes that sort of thing). Similarly, coding a solution that allows cancelling a query would also require significant API changes and again special efforts for each db driver. 

I'm not really using SQLPad much beyond it being a companion tool while working against a development database. 

If anyone wants to dig into this stuff and fix it I'm open to PRs improving this, but I personally won't be putting any effort into it.

**Comment by Shadow00Caster** [comment]
@rickbergfalk I am running latest via docker (3.4.0 at time of writing) and have added
`; HTTP server timeout as number of seconds. Extend as necessary for long running queries
timeoutSeconds=480`
into my sqlpad.ini which is pointed to via env var `SQLPAD_CONFIG /var/lib/sqlpad/sqlpad.ini`, however I still experience MSSQL queries that take longer than 2 minutes to timeout exactly at the 2 minute mark.
