### ISSUE TITLE
Crazy feature request: integrate Tatiyant's PostgreSQL explain visualizer

### ISSUE THREAD

**Issue by jakeonrails** [rickbergfalk/sqlpad#164]
https://github.com/AlexTatiyants/pev is the repo, it is also a Node app. I do not know how easy it would be to make this work within SQLPad or if it is even the sort of feature that the SQLPad maintainers have in mind/vision.

All I know is that as easy as it is to copy/paste output and then go through the process of adding it to PEV manually, it would be so nice to just have a button I could click to visualize the query within my SQL tool.

For those who don't know PEV takes the output from an EXPLAIN ANALYZE and draws a very useful diagram to make it easier to understand how your query works. If you haven't tried it out I highly recommend it, you can test it here: http://tatiyants.com/pev/#/about

**Comment by rickbergfalk** [comment]
Hi @jakeonrails - I haven't seen this project yet but it looks great! 

Unfortunately while it is built with node/javascript, its done so with Angular and TypeScript libraries, so I'm not entirely sure how to go about integrating it without porting it to React (which sqlpad uses). 

Regarding feature fit, I could go either way. I could see query plan visualization being a really useful addition, but it is kind of outside the core focus of sqlpad... I'd be curious to hear other peoples thoughts.

**Comment by rickbergfalk** [comment]
Giving it some thought and reviewing the project again... I think implementing this specifically would be a bit out of scope since it is a bit postgres specific. With less time to support this project I'm trying to limit the one off features :)

I would love for PEV to be integrated to a SQL editor... but I think it'd just need to be one that is postgres specific
