### ISSUE TITLE
Newbie issue with signup

### ISSUE THREAD

**Issue by miguelpaz** [rickbergfalk/sqlpad#171]
I downloaded SQLPad and used it and no longer have the password that I created the first time. I followed the step to get the "admin rights back"  by running `sqlpad --admin myemailaddress@domain.com` however I keep getting request for sign in or sign up and does not allow me to reuse the same email address. When I try other emails I get a message "email not whitelisted".
Any advice would be great.

**Comment by rickbergfalk** [comment]
Hi @miguelpaz  - apologies for running into this scenario! There should really be a reset-password option via the cli too. 

The easiest way to get back in would be to stop sqlpad, then rename (or delete) the users.db file in the sqlpad database directory. By default this file is located at $HOME/sqlpad/db but you might have overridden that via a command line argument. 

Once the file is missing, start sqlpad. You should be able to go to the signup page and it'll be open-administration like first install. All your queries/connections should be kept in place.

The users.db file is just a line-delimited JSON file, so if you are curious about its contents or need to modify user data behind the scenes you can poke around in those files. You won't be able to change the password manually though since it is hashed. 

Let me know how it goes :)

**Comment by miguelpaz** [comment]
It worked 👍 
Thanks a lot!

**Comment by rickbergfalk** [comment]
You're welcome!
