### ISSUE TITLE
Multiple recordsets

### ISSUE THREAD

**Issue by georgir** [rickbergfalk/sqlpad#177]
Currently if you add two select statements in the same query, you get their results displayed in one single table with no clear separator; If the two recordsets have some different columns, the table displays only the columns of the first recordset, and shows NaN/null where the field is missing in the second recordset.

Displaying each result recordset in a separate table would make more sense.
[Applies to DB connection drivers that support multiple recordsets, such as MS SQL. Not sure if all do.]

**Comment by rickbergfalk** [comment]
Hi @georgir - Unfortunately as I understand it, this is more of a SQL Server thing. Postgres for example supports returning results of multiple queries, but the column signature is expected to be the same.

Since sqlpad isn't tied too strongly to certain features of a particular database, I'm not sure it'd be worth the effort and potential complication of adding support in for this sort of scenario.

I'd be willing to consider a pull request for this though if someone wants to take the time and figure this out. 

Alternatively, what if for SQL Server only the results of the first query were returned? Would a more accurate single result set be more ideal that a mixed result set?

**Comment by rickbergfalk** [comment]
I'm closing this ticket but not opposed to a PR if someone works on getting this in that also plays well with other databases. I just personally won't have the time or resources to work on this one.
