### ISSUE TITLE
Provide database selector for server in query UI

### ISSUE THREAD

**Issue by lishoujun** [rickbergfalk/sqlpad#199]
![image](https://user-images.githubusercontent.com/8399413/27947494-a10cdc06-6328-11e7-93fd-0f2fb866d173.png)

**Comment by vweevers** [comment]
If by "default database" you mean "last used database", i.e. when you create a new query it auto-selects the database used in your last query, then +1. And it has to be saved per user, not globally.

**Comment by rickbergfalk** [comment]
@vweevers I really like that idea! 

@lishoujun Which database are you using? Are you using MySQL? 

Looking at that picture it seems like a database is selected. If this is MySQL, I'm wondering if this is related to #198 and MySQL databases are listed in the schema tree...

**Comment by lishoujun** [comment]
@rickbergfalk   
yes MySQL  
and 
no it is not related to #198 , I haven't set database in Connection

**Comment by rickbergfalk** [comment]
I realized this request is more about defining a connection without specifying a database (or maybe a default database) and then allowing the user to select the specific database within the query editor (instead of potentially having to create a connection for each one...) That could be useful but might only be applicable for certain platforms?

**Comment by rickbergfalk** [comment]
I added another issue to also track the connection dropdown defaulting to last used. Not that I've had much time for this lately but it feels good to organize these issues :)

**Comment by lishoujun** [comment]
OK

**Comment by rickbergfalk** [comment]
Don't see ever adding a way to select the database from sidebar unfortunately. It'd require adding a new concept to the UI and db config, and it is just not something I see myself using personally. It could also get complicated as only some databases support that kind of thing...

However, v3 does finally remember the last used connection, so that's something...
