### ISSUE TITLE
Rounding of numbers, even if they are strings

### ISSUE THREAD

**Issue by spike01** [rickbergfalk/sqlpad#200]
Hi there,

I've noticed some strange behaviour in sqlpad - really large "numbers" get rounded up in the UI, even though they are stored in the db as varchar.

Example:

![image](https://user-images.githubusercontent.com/7307631/28209250-a10f8148-6889-11e7-8a1c-bf064bd1eaa9.png)

**Comment by rickbergfalk** [comment]
Thanks for reporting @spike01! It looks like this is happening because of the additional number parsing stuff SQLPad does on the server side. 

Some db drivers in node return BIGINTs as strings of text to deal with JavaScripts inability to handle large numbers. To counter that SQLPad detects number strings and converts them back to numbers at the loss of precision... but this isn't at all useful in your example above.

I think the solution to this is to delay converting of values until absolutely necessary (like when a dataset is charted).

**Comment by rickbergfalk** [comment]
Fixed in #215 - Fix will be in next release, hopefully later this weekend
