### ISSUE TITLE
No data shown when excuting any query

### ISSUE THREAD

**Issue by shehanster** [rickbergfalk/sqlpad#228]
Hi, 

After installing sql pad version 2.3.0  with node js 6.11.3 and npm version 3.10.10 I'm not seeing any results when executing any query.  
Please refer screen shot below

I have use mysql user with select grant. databases and tables can bee seen on the left panel. 

![screenshot from 2017-09-21 14-30-31](https://user-images.githubusercontent.com/18304392/30687813-0dd15b22-9eda-11e7-99e0-192f154de8be.png)

**Comment by rickbergfalk** [comment]
Hi @shehanster - May I ask what your query is that you are running? It looks like you're getting results back from a query other than a SELECT statement...

**Comment by shehanster** [comment]
its a  basic select query run on the DB with user having only select grants . 

please find the screenshot below. 
![screenshot from 2017](https://user-images.githubusercontent.com/18304392/30794144-2835bf3c-a1e4-11e7-9317-f2b7b7346e7d.jpg)

**Comment by rickbergfalk** [comment]
Ah I see - the issue is from the USE statement prior to the SELECT. SQLPad currently runs a single query statement, and does so with a new connection each execution.

You have a couple options. You can put the schema/database name in the connection setup, which will allow you to query that schema by default. Otherwise you can specify the full object path,  `SELECT * FROM schema.tablename`.

**Comment by shehanster** [comment]
works now thanks!
