### ISSUE TITLE
Case-Sensitive Collation

### ISSUE THREAD

**Issue by LeandroFavero** [rickbergfalk/sqlpad#271]
The database in Microsoft SQL use a case-sensitive collation and this can´t be change :-(
And I´m getting this error: Invalid object name 'INFORMATION_SCHEMA.tables'

Are there some parameter to setup? Because the query must be 'INFORMATION_SCHEMA.TABLES' to work.

**Comment by rickbergfalk** [comment]
Hi Leandro - are you able to change the SQL to TABLES and COLUMNS in this file and see if that fixes it? https://github.com/rickbergfalk/sqlpad/blob/master/lib/get-schema-for-connection.js

I wasn't aware case-sensitive collation impacted the table name references - I thought it was only for the values...

If upper case TABLES/COLUMNS works I think we'd be safe to make the change since the case insensitive dbs shouldn't care

**Comment by LeandroFavero** [comment]
Works!! 

function getStandardSchemaSql(whereSql = '') {
  return `
    SELECT 
      (CASE t.table_type WHEN 'BASE TABLE' THEN 'Tables' WHEN 'VIEW' THEN 'Views' ELSE t.table_type END) AS table_type, 
      t.table_schema, 
      t.table_name, 
      c.column_name, 
      c.data_type, 
      c.is_nullable 
    FROM 
      INFORMATION_SCHEMA.TABLES t 
      JOIN INFORMATION_SCHEMA.COLUMNS c ON t.table_schema = c.table_schema AND t.table_name = c.table_name 
    ${whereSql}
    ORDER BY 
      t.table_type, 
      t.table_schema, 
      t.table_name, 
      c.ordinal_position
  `
}

**Comment by rickbergfalk** [comment]
Thanks for checking on this @LeandroFavero! I've made this change and published to npm as version 2.4.2.
