### ISSUE TITLE
Mobile (responsible interface)

### ISSUE THREAD

**Issue by LeandroFavero** [rickbergfalk/sqlpad#277]
First: Great job! SQL Pad is very nice tools.

I would like to suggest a responsible interface, to mobile use.
Because, in a emergency (this happens 10 minutes ago), we can check the database from smartphone (in holiday for example).
I had success using a iPhone 7 Plus, but was really hard, because interface was a mess.

What you think?

**Comment by rickbergfalk** [comment]
Thanks @LeandroFavero 

Since SQLPad's initial use case was data exploration and charting, the mobile interface wasn't a high priority. (Also isn't SQL on a phone keyboard hard?)

I am in the process of reworking some of the front-end styling though and can keep this in mind as I go through it.

I don't know that I can commit to the mobile interface being a priority, but I think things can be done to make it more manageable :)

**Comment by rickbergfalk** [comment]
I know its been a while since this issue was opened, but I've decided against implementing a responsive interface. A couple of the libraries in use on the front-end don't play well with mobile anyways, so it'd require a rethink of the UX... A SQL tool for the phone sounds like it'd be an interesting problem to tackle though.
