### ISSUE TITLE
newbies

### ISSUE THREAD

**Issue by vildor** [rickbergfalk/sqlpad#316]
not able to create a connection.

http://localhost:3001/connections#connection 
TEST FAIL

Went i try a query, I got this error
Error: getaddrinfo ENOTFOUND http://localhost http://localhost:5432

-----
Usely I connect with go like this
db, err := sql.Open("postgres", "host=localhost port=5432 user=XXuserXX dbname=gorm password=XXpassXX sslmode=disable")
----
My install process
cd sqlpad/docker
docker build -t sqlpad .
docker run --restart=always -d --name s1 -p 3001:3000 -v /mnt/3a929d35-a02c-4c4d-8198-de3ee6fd0d53/technology/javascript/docker/volumes:/var/lib/sqlpad -d sqlpad
firefox localhost:3001
sing up
a@a.ca
a

**Comment by vildor** [comment]
Sorry my mistake, I need to remplace localhost by 192.168.2.102 to acces my other container.

**Comment by rickbergfalk** [comment]
Hi @vildor - No worries. Did you get it all working now?

If postgres is also in a container, you could use docker-compose to put your containers on a docker network, and refer to that container by name instead of localhost or the ip address. 

I'm going to close this issue but feel free to let me know if you have any more questions.
