### ISSUE TITLE
Support of Sybase

### ISSUE THREAD

**Issue by matnoublanche** [rickbergfalk/sqlpad#374]
Hi there,

Is it planned to support Sybase database ?

**Comment by rickbergfalk** [comment]
Not directly. Support for generic unixodbc database connections in the works however. Once that is added connecting via odbc might be an option?

**Comment by clach04** [comment]
@matnoublanche, UnixODBC support just got merged in, https://github.com/rickbergfalk/sqlpad/tree/master/server/drivers/unixodbc - its worth giving that a shot assuming you have an ODBC driver available.

**Comment by matnoublanche** [comment]
@rickbergfalk @clach04 Thank you for your answers :)
I'll test with an ODBC driver

**Comment by rickbergfalk** [comment]
I've published an updated build of SQLPad to npm that has the odbc module as an optional dependency. As long as your setup meets the necessary requirements, I think is should work.

Because this is something I personally don't have set up, I've started a wiki page for ODBC help. If there is anything missing or if there is some additional info that would be helpful please feel free to add it.

I'm going to close this issue, but feel free to keep the conversation going here and we can reopen if necessary :)

**Comment by rickbergfalk** [comment]
Link to referenced wiki page https://github.com/rickbergfalk/sqlpad/wiki/ODBC

**Comment by clach04** [comment]
Thanks @rickbergfalk, I went ahead and added some notes to that page. There are notes there are on how to get sqlite up and running under Ubuntu/Debian as well as Vector (on Hadoop) , Actian X, and Ingres.
