### ISSUE TITLE
Can it support close register new account by admin?

### ISSUE THREAD

**Issue by Cooomma** [rickbergfalk/sqlpad#380]
I think that oauth is very cool, but it still need a more detail auth when in a medium-large groups of users. This feature seems to Jenkins register can be configure in panel. It turns on when admin need to add a new member, and turns off when register completed. 

Hope to see it can be configuration in configuration.

Thanks for creating this fantastic SQL tools!!!!

**Comment by rickbergfalk** [comment]
Thanks @Cooomma!

I'm not sure I understand this request entirely but I'll look into how Jenkins handles registration. 

How OAuth works in SQLPad today is that a user must first be whitelisted or invited. Only then will they be able to log in via google auth. Alternatively the admin could whitelist for an entire domain, so only email addresses for a particular org would work.

**Comment by rickbergfalk** [comment]
Sorry for the nearly year gap in response 😅 

I'm not sure if this would address the need, but setting `disableUserpassAuth` to `true` would disable local authentication, and not setting `whitelistedDomains` would require individual email addresses to be added as users. They wouldn't log in with local credentials, and would still need to authenticate with Google. For the initial user, you'd still set the `admin` email address so that you have an initial log in.

The admin registration UI should be disabled once an admin user exists in the users db.
