### ISSUE TITLE
Support Oracle

### ISSUE THREAD

**Issue by gdebuz** [rickbergfalk/sqlpad#382]
Hello,

I'm very interrested by your product SQLPad... but my DB is an Oracle DB!
I've seen in a post of 2015 that you were opened to open your application if there were a oracle's javascript library - that your contributor had found at https://github.com/oracle/node-oracledb
So are you now able to integrate this Oracle compatibility to your product, that seems to be a great product for our goals!

Thank you for your work!

**Comment by rickbergfalk** [comment]
Thanks @gdebuz!

While the referenced library is a Node.js library, it requires compiling native dependencies, and has a quite complicated setup. In the past those kinds of modules have been restricted, because it complicates the install or build process. 

Recently however we've added an optional native dependency for linux ODBC. 

I could see this being added in a similar way... partially added with a warning that you'd need to follow the Oracle driver setup instructions to get it working fully (https://oracle.github.io/node-oracledb/INSTALL.html#quickstart). 

I'd be open to adding this to the project, but testing would be difficult.

Unfortunately I'm not able to give you any idea on when this would happen. I started some larger changes in the project over the summer, and haven't had much time to get back to them. Hope to get back to this project soon though.

**Comment by rickbergfalk** [comment]
Unfortunately I'm going to pass on adding Oracle support to SQLPad. Reviewing the Oracle driver documentation for Node.js, the setup is still quite complex. Native dependencies added for ODBC trip some people up, and I can only imagine adding more of this will cause more confusion.

Supporting Oracle would be difficult to test as well...

**Comment by baikal** [comment]
... just a little addon, maybe of use for someone hitting this issue when googling **sqlpad** and **oracle** ...


Oracle works quite well using unixODBC on linux, with the oracle "instantclient" installed and configured. The following [Database SQL for lookup schema] shows all schema/table/columns incl. column-comments in SQLPADs schema-sidebar, omitting all the system schemas and whatnot from oracle.

```SQL
SELECT
  owner AS table_schema,
  table_name,
  column_name,
  comments AS column_description,
  data_type
FROM
  all_tab_columns
  LEFT JOIN all_col_comments
    USING(owner, table_name, column_name)
WHERE
  owner NOT IN (
    SELECT username
    FROM all_users
    WHERE oracle_maintained = 'Y'
  )
ORDER BY
  owner,
  table_name,
  column_id
;
```

@rickbergfalk feel free to add to some documentation if see fit
