### ISSUE TITLE
Google BigQuery Support?

### ISSUE THREAD

**Issue by hongkongkiwi** [rickbergfalk/sqlpad#395]
Hi there,

Is it possible to support Google BigQuery? I'm looking for an easier way to write queries using this platform.

**Comment by rickbergfalk** [comment]
Sure! I'd be willing to accept a pull request if you wanted to take a shot at it. Otherwise it might be a while until I get to it... 

It looks like google has a node driver/module available: https://github.com/googleapis/nodejs-bigquery. 

The "driver" connection/interface would need to be implemented, following the patterns established here: https://github.com/rickbergfalk/sqlpad/tree/master/server/drivers.

**Comment by hongkongkiwi** [comment]
I've used the bigquery node code before for a simple project.

I will have a look at the mysql driver as reference, any additional driver docs would be helpful (?) if any.

**Comment by rickbergfalk** [comment]
Not too much on the way of documentation unfortunately. Best I could recommend would be to check a few of the implementations. SQLPad will do some validation of the driver interface to try and ensure it is conforms to what it expects. Let me know if you have any questions

**Comment by hongkongkiwi** [comment]
A couple of updates on this, I'm definitely making progress.

There are a couple of additional things which are different:
- BQ supports Arrays (so I will return array type)
- BQ supports Records (so I will return the record type)
- BQ requires authentication before we can run tests, I will set these so they can be passed via environment variable. Querying will be done with the free datasets but you still need some credentials
- To Simplify things I'm just using a service account, we can add user account authentication at a later stage.

**Comment by bruth** [comment]
Hi there! Any progress by anyone on this? I have a need for accessing BQ.. is there anything I can contribute or test to get this going again?

**Comment by murphyke** [comment]
I work with @bruth. I see that @hongkongkiwi forked to add bigquery support in https://github.com/hongkongkiwi/sqlpad. He added [substantial work in three commits](https://github.com/rickbergfalk/sqlpad/compare/rickbergfalk:master...hongkongkiwi:master).

Apparent progress in implementing the required interface:
- [ ] runQuery - POC synchronous code present; async and error-handling still TODO
- [x] testConnection
- [x] getSchema
- [x] fields

There is a tests.js that has been tweaked for bigquery using a public dataset.

Superficially it looks pretty close! I can look at it further shortly.

@hongkongkiwi Can I assume since it's been a while that you are not working on this anymore? If so, we can take this and run with it; do you remember if you ran into any problems that we should know about before we dig in?

**Comment by bruth** [comment]
Just noting this was implemented #572

**Comment by rickbergfalk** [comment]
I've officially tagged the 4.2 release. Thanks @bruth @murphyke for your work on this!

**Comment by murphyke** [comment]
> I've officially tagged the 4.2 release. Thanks @bruth @murphyke for your work on this!

And @hessam61, who submitted the other PR from our group!

**Comment by rickbergfalk** [comment]
Yes @hessam61 too! The assistance is much appreciated :)
