### ISSUE TITLE
Sqlpad calling rest api which delivers json payload with query results

### ISSUE THREAD

**Issue by keane123** [rickbergfalk/sqlpad#439]
Hi Rick , more of a question. I have a custom springboot api  that takes your username password and sql and returns a result set. It has apache spark sqlcontext below it along with the presto api. The rest api manages tokens and has a hook into apache ranger for authorisations. I have thus eliminated jdbc . Was looking at sqlpad  or writing a React Cue or Angular UI ....Not sure sqlpad can hook into a restful endpoint ? Advantages of my all is that I capture all user sql and store in a graphs and elasticsearch.

**Comment by rickbergfalk** [comment]
Are you looking to use only the front end of SQLPad or the back end as well? 

If using the back end/server piece of SQLPad, you could add an HTTP driver to SQLPad that calls your API and formats the responses to what SQLPad expects. Since the data transformations would be specific to your stack this would likely be something you'd just do in a fork of SQLPad.

Alternatively you are building your own UI, you could potentially use the code in the client directory as a starting point, and integrate it with your APIs.

**Comment by keane123** [comment]
Thanx Rick , looking at this stage to client only. Was trying to figure out whether there was any point in taking the backend as well. In future releases are there any plans to source data from Apis ? I'm in the big data space and I see a real movement to api cos of all the variety of db sources and engines.

**Comment by rickbergfalk** [comment]
Regarding APIs... Not really. Unless the API took SQL as an input potentially? The presto db driver for example uses an HTTP-based API, so I could see more of that kind of thing being done. 

I suppose if the API is exposed and open there could be a static front end only version of SQLPad in the future that could talk to it?

I'm trying to figure out what the future of SQLPad looks like to be honest. I'm in full support of people taking pieces of SQLPad and turning them into something else :)
