### ISSUE TITLE
Mysql set port 33068

### ISSUE THREAD

**Issue by jamesou168** [rickbergfalk/sqlpad#5]
Hi，I'd like to set mysql port  33068 on sqlpad ,rather than 3306.How to do?

**Comment by jamesou168** [comment]
Can i modify the source code to extend the function that is input the database's port on the "Add Connection" page ?

**Comment by jamesou168** [comment]
![qq 20150209165208](https://cloud.githubusercontent.com/assets/7066642/6103179/079e8a58-b07c-11e4-96c9-75fc2fb8a4d6.jpg)
I have done the function ,if you want to add to your source code,i can send these files to you.thanks.

**Comment by dcelasun** [comment]
Yes, this is indeed a problem for the MySQL driver since it requires the port in a [separate field](https://www.npmjs.com/package/mysql#connection-options).

You are very welcome to send a PR, but please make sure it's generic enough to support all existing drivers, not just MySQL.

If not, I could probably tackle this myself in a few days.

**Comment by jamesou168** [comment]
I'm not familiar with sqlpad.I just only add the function for MYSQL.I am afraid to bring new bugs if i would  adapt other existing drivers. ：）  Thx.

**Comment by dcelasun** [comment]
That's no problem, I'll add the feature today myself :)

**Comment by dcelasun** [comment]
Apologies for the delay, you can now configure the port for each connection. Leaving it empty will use the default port for each driver.
