### ISSUE TITLE
sqlpad features

### ISSUE THREAD

**Issue by msaleh97** [rickbergfalk/sqlpad#517]
Hello,

I had a couple of questions regarding sqlpad:

1- Is there a way to allow users to create/delete their own connections?
2- Is there a way to prevent users from seeing connections they don't have access to?
3- Would I need to add each user individually if I enable SAML Authentication? 

Loving the product so far! Thank you!

**Comment by rickbergfalk** [comment]
Hi @msaleh97 glad you're finding the project useful! To answer your questions:

> 1- Is there a way to allow users to create/delete their own connections?

Unfortunately there is not. Today the implementation allows admins to create connections. By default they are available to everyone, but you can turn this off and assign access to connections on a user basis. "editor" users can use connections and run queries, but otherwise can't modify them. 

I could see a case for changing the way this is managed to something like "everyone can create connections that are private by default, and can be shared with everyone or certain individuals". This would also affect the query ownership model as well though, as all queries are shared by default as well, but this doesn't work when connections are not available. 

> 2- Is there a way to prevent users from seeing connections they don't have access to?

There is but users wouldn't be able to manage their own. Here's how you would have to go about it today:
* Set `SQLPAD_ALLOW_CONNECTION_ACCESS_TO_EVERYONE` to false, which would require connections to be manually assigned to specific users.
* Add users running queries as "editors"
* Create connections with an "admin" user, manually assigning connection access to editors

> 3- Would I need to add each user individually if I enable SAML Authentication?

Yes that looks to be the case. I can see the case to have an auto-user creation option added for SAML however. (The Google auth implementation honors a domain whitelist that auto-adds users if the email domain is a match)

**Comment by msaleh97** [comment]
Thanks! One more question, is there plans to allow users to access the application directly without them logging in? They can all be editors by default and the connection would be defined in the config file.

**Comment by rickbergfalk** [comment]
Sort of like a shared public user of sorts? 

If so its been something I've been thinking a lot about but nothing implemented. It is something I'd like to add, but hard to commit to a timeline.

**Comment by rickbergfalk** [comment]
Jut to loop back on this -- an option to disable authentication has been added to SQLPad https://rickbergfalk.github.io/sqlpad/#/authentication?id=no-authentication. 

Going to close this for now but feel free to reach out if you have additional questions!
