### ISSUE TITLE
Export to .xlsx datetime column converted to  just date

### ISSUE THREAD

**Issue by deepvoice** [rickbergfalk/sqlpad#60]
Query result columns are correct but fine but after exporting to .xlsx it displays only date. CSV is also correct.
Datetime in this format: YYYY-MM-DDTHH:MM:SS.000Z
Example: 2015-11-11T12:30:45.000Z

Maybe it is just a function of xlsx that it doesn't understand this datetime format?

**Comment by rickbergfalk** [comment]
It looks like the value is there in the file, but Excel is displaying it as a date instead of datetime. If you change the cell formatting, or look at the formula bar, the time should show up.

SqlPad's just pushing values through https://www.npmjs.com/package/node-xlsx for convenience which  builds on top of https://www.npmjs.com/package/xlsx. 

Maybe there's a way to set the datatype or formatting of the cell behind the scenes? 

If anyone wants to dive deeper into xlsx rendering feel free :)

**Comment by deepvoice** [comment]
Thank you! I will look into it :)
