### ISSUE TITLE
send each run query to slack

### ISSUE THREAD

**Issue by arbabnazar** [rickbergfalk/sqlpad#627]
Sorry about if it's not an issue but I could find help about it. I have old working sqlpad server which send each run query to slack. Result are something like this on slack:
```
New Query run by abc@def.com on SQLPad
select * from announce where name_by = xyz and accessed_at  > 1454076800;
```

While I have configured new sqlpad server but could find any option to send each running query to slack rather send the saved queries to slack.

Can somebody point where I can find this or configure it

**Comment by rickbergfalk** [comment]
Hi @arbabnazar -- setting `slackWebhook` in config should do it. If you have access to the old sqlpad you should be able to set it to the same value https://rickbergfalk.github.io/sqlpad/#/configuration?id=slackwebhook

If that isn't working for whatever reason let me know

**Comment by arbabnazar** [comment]
Hi @rickbergfalk thanks for the reply, I have setup the webhook on the new server and it's only post to the slack, when I saved the query like this:

```
New Query </sqlpad/queries/aYqnAhURJtqwJafN|Entity Users daily login>
           saved by abc@def.com on SQLPad
           
            select name from user_login_history
```

while the old one post every query that execute by any user.

Hope you got my point.

Thanks,

**Comment by rickbergfalk** [comment]
@arbabnazar I was looking through history and I'm not sure if it did send a message every query run. I think it is something worth adding though.

I'm actually thinking about adding lots of webhooks actually, so that people can kind of extend SQLPad to whatever use they want, and I can ditch specific integrations like slack. 

For example, I'm thinking about adding a hook for sending the query results when a query is run as well, hooks for when a user is invited so an email/slack/other system message can be sent, etc.

**Comment by rickbergfalk** [comment]
@arbabnazar I've just implemented webhooks, which have a hook for each query run.

These hooks are not designed for slack specifically however, so you'll need to stand up a small service to do what you'd like with the data. 

Unfortunately I won't be building specific slack integrations, as its more than I'd like to maintain at the moment. The generic actions allow for ultimate flexibility. 

If there's interest, I could potentially provide a simple example written in node.

**Comment by arbabnazar** [comment]
@rickbergfalk Can you please give me the example of this implementation that you did if possible.
