### ISSUE TITLE
MS SQL connection with named instance and specific port

### ISSUE THREAD

**Issue by chandrabe** [rickbergfalk/sqlpad#70]
Hello,

How can I connect to a MS SQL Server using a named instance and a specific port ?

I tried to pass the instance name in the server field as servername\instance and the port in the port field but with no success.

I saw in the Tedious driver documentation that instance and port option where mutually exclusive.
Do this means this is a no go ?

Regards
Olivier

**Comment by rickbergfalk** [comment]
Hi @chandrabe 

Interesting. Which port are you using?

I did some quick research and according to the node-mssql module, it looks like port 1444 runs the SQL Server Browser service, so that must be how it manages connections to different instances? I had no idea...

Could you try connecting with servername\instance in the server field and manually setting port to 1444? 

If that doesn't help I'll have to do some experimenting with the way SQL Server connections are handled.

**Comment by rickbergfalk** [comment]
Hi @chandrabe - was there any luck with this? 

I'm going to close this for now but please let me know if it should be re-opened.
