### ISSUE TITLE
LDAP/AD details 

### ISSUE THREAD

**Issue by eladeyal-intel** [rickbergfalk/sqlpad#709]
Some things are not clear to me with LDAP.

1. If a user is to be authenticated by LDAP - does she need pre-creation of sqlpad user by admin? This should be documented in authentication.md

2. Is it possible to enable LDAP authentication while disabling local username registration? (It should be possible in an enterprise environment. Looking at the code I'm not sure this is possible). This should be documented in authentication.md

3. Add a URL example LDAP_URL to configuration.md - I took the example from http://www.passportjs.org/packages/passport-ldapauth/ . Is that correct? are both LDAP and LDAPS supported? #707 

@dengc367

**Comment by dengc367** [comment]
@eladeyal-intel 
I think admin should pre-create the ldap email(eg:  username@xxx.com) in sqlpad, so the admin can control the process to authentication and authority of the user, because configuration roles is in the sqlpad metadata database, and we should mapping the user and role.
Of course, if no pre-creation of ldap user by admin, we can still give the default authority to the user.

**Comment by eladeyal-intel** [comment]
I did not understand @dengc367  response to #1 and #2. I think things like that should be documented. (And then maybe changed if needed). I will not be using LDAP myself.

**Comment by dengc367** [comment]
@eladeyal-intel Sorry, I misunderstood your meaning before. OK, I will update it in [authentication.md](docs/authentication.md) and #707  wait for a monent.

**Comment by dengc367** [comment]
@eladeyal-intel  PR #738 submitted, please check. thanks.
