### ISSUE TITLE
_.sortByOrder is not a function

### ISSUE THREAD

**Issue by dlabey** [rickbergfalk/sqlpad#75]
When trying to use sort on charting it looks like the current version of underscore does not support it... maybe switch to lodash?

**Comment by rickbergfalk** [comment]
Hi @dlabey 

I believe tauCharts depends on underscore. And I'm not certain, but I might have used lodash via browserify prior to that, which seems somewhat redundant.

I was actually contemplating removing the sort functionality from the charting UI, since sorting can be done in the query, and the order of the results will influence the chart that is generated...

Any strong  preferences on whether sorting should be fixed vs removed all together?

**Comment by dlabey** [comment]
In that case yes we can order it through SQL and I think it's best to get rid of.

**Comment by rickbergfalk** [comment]
I am planning on removing this next SqlPad release. Any thoughts on how this change should be versioned? 

It used to work at one point... so in a way I'm removing a feature which someone may have counted on previously. So is this a "breaking" major change? or is this a minor feature? Or just a patch?

SqlPad isn't something thats depended on programmatically either, so I'm unsure how this all fits together.

I'm leaning to a minor feature versioning personally...

**Comment by dlabey** [comment]
I think that would be appropriate.

**Comment by rickbergfalk** [comment]
forgot to close this - this was addressed in 1.15.0
