### ISSUE TITLE
Date column types are forcible localized

### ISSUE THREAD

**Issue by dlabey** [rickbergfalk/sqlpad#77]
This is rather annoying in some cases when localization needs to be done through SQL because the date output is by day and not hour (which is required to properly localize). Can this be made into an option?

**Comment by nickcarenza** [comment]
An example of this would be when using `date_trunc`.

When i run this query `select getdate(), date_trunc('day',getdate());`

I get:

```
getdate             date_trunc
01/08/2016 18:56:27 01/07/2016 21:00:00
```

when i would expect:

```
getdate             date_trunc
01/08/2016 18:56:27 01/08/2016 21:00:00
```

**Comment by rickbergfalk** [comment]
Ah yes I've been meaning to look into this. This is with SQL Server right? 

If I remember right, everything is being parsed as a UTC date in the browser when consuming the query result JSON even if it isn't. From what I've done in Postgres this works out but SQL Server's date times have all been off unless you are returning UTC dates. For example try:

```sql
SELECT GETDATE() AS GetDate, GETUTCDATE() AS GetUTCDate
``` 

What if this localized times that had a timezone but otherwise didn't? Or would it be preferred to have this something toggled on or off?

**Comment by nickcarenza** [comment]
This was done with Redshift

**Comment by dlabey** [comment]
I've made a pull request that allows flexibility on this issue

**Comment by rickbergfalk** [comment]
@nickcarenza meant to follow up on this but SqlPad works with Redshift? 

I've read that Redshift can use some postgres db drivers but I've heard some reports of SqlPad not connecting to Redshift in the past. I figured something about the Node.js Postgres driver wasn't compatible...

**Comment by nickcarenza** [comment]
@rickbergfalk thanks for the followup. I have experienced no other issues. :+1:
