### ISSUE TITLE
Code Readability / Logic flow

### ISSUE THREAD

**Issue by srhyne** [rickbergfalk/sqlpad#79]
Hi Rick, 

Congrats on the success of sqlpad. It's a very important project I think as there are only a few expensive solutions for this sort of thing in the market so your contribution is huge. Great work! 

One suggestion I would like to make for making your logic a little cleaner is to return early and return often. 

Example.. 

https://github.com/rickbergfalk/sqlpad/blob/master/routes/onboarding.js#L36

Instead of nesting the entire signup success logic in an else statement just return the error first. 

`return res.render('signup', {message: 'passwords are not match'});`

Another example of where you can just return early and reduce the christmas tree affect...

https://github.com/rickbergfalk/sqlpad/blob/master/routes/onboarding.js#L71

I'm sorry if this comes off as petty but I do think that clean, easy to follow code helps to increase contribution rates. 

Again, I think your work is fantastic. Just trying to help.

**Comment by rickbergfalk** [comment]
Hi Stephen,

Thanks for the kind words and the constructive feedback! This is helpful and welcome. Javascript and web development is mostly a hobby for me. By profession I'm a SQL Server Developer/DBA. 

I've been interested in ways I could better organize my code or structure the application.

In fact since starting SqlPad I realized modules were cached when required(), so requiring once and passing objects on the express app object is unnecessary. 

I've also been tempted to create a models/data access layer for things like users and queries, to better isolate that code, facilitate testing, and provide clarity as to what a user or query object looks like to SqlPad.

If you've noticed any other improvements that could be made feel free to send them my way :)

(And this goes to anyone else out there reading this too)

**Comment by srhyne** [comment]
Rick, well kudos to you for going out of your comfort zone to build this. I have a lot to learn about SQL!

**Comment by ghedwards** [comment]
Kudos, I'd love to help with this project as well. Any particular reason you went with Ace editor over Codemirror? I've already got a version of your editor using Codemirror, it can support table context help.

**Comment by rickbergfalk** [comment]
Thanks @ghedwards. I had used codemirror for a previous project and wanted to try Ace. I also found the api/configuration/documentation to be more my style. Is there a particular strength codemirror has over ace these days?

I'll have to check out the table context help in your fork. I was just thinking about what it would take to add some form of autocomplete for database objects...

**Comment by ghedwards** [comment]
Codemirror seems to be a little more open and better documented and more adopted, I guess because they don't have a commercial offering? 

Anyway, it seems Ace has a autocomplete API as well, though documentation is hard to come by, but I found this. http://plnkr.co/edit/6MVntVmXYUbjR0DI82Cr?p=preview
