### ISSUE TITLE
generic ldap authentication vs Active Directory

### ISSUE THREAD

**Issue by skaravad** [rickbergfalk/sqlpad#831]
Hello, 
First, thank you so much for all your efforts in building sqlpad, my users are quickly adopting this tool as their go to SQL workbench.

Now to the current issue, I see that sqlpad is currently integrated only to work with Active Directory out of the box. It would be great if this can be a generic ldap authentication so that users can set the search filters and top of it Active Directory is a different beast. Though I can use Auth Proxy , the user experience might be little different (I suppose form login vs pop-up login at proxy level).

**Comment by eladeyal-intel** [comment]
I think sqlpad uses https://github.com/gheeres/node-activedirectory which was not updated since 2016. My comment there https://github.com/gheeres/node-activedirectory/issues/224 (which would help LDAP authentication) wend unnoticed. perhaps this library should be replaced with something which is being maintained.

@dengc367

**Comment by eladeyal-intel** [comment]
BTW @skaravad OpenID Connect and SAML are also supported out of the box.

**Comment by skaravad** [comment]
Thank you @eladeyal-intel , I feel that setting up LDAP and supporting the product with authentication and authorization is much more useful as most orgs do have LDAP and also dev env setup is much easy (ApacheDS , openLDAP) for sure (SAML and OpenID need some additional config , which can be quite some work).
Another reason to support LDAP (generic LDAP) , many great OSS support LDAP (i'd day 90%) vs 10 %  trying to support SAML etc. 
 
Again thank you so much for the response and the contributions towards this project, this is a lifesaver.

**Comment by eladeyal-intel** [comment]
Maybe http://www.passportjs.org/packages/passport-ldapauth?

**Comment by rickbergfalk** [comment]
passport-ldapauth looks like a good option, but looks like there are issues with node 10. Unsure if they are fixed in node 12 or later. 

I haven't looked at the configuration for `passport-ldapauth`, but if it is different or incompatible with existing, would this require a breaking change? Existing "ldap" authentication config should probably change naming to active directory...

**Comment by dengc367** [comment]
@eladeyal-intel OK, I will try to substitute with `passport-ldapauth`, `openldap` and `activedirectory` can unite the configuration in principle.

**Comment by dengc367** [comment]
@eladeyal-intel  #834 PR is created, you can review the code now.

**Comment by dengc367** [comment]
PR #834 can be merged now, so close this issue.

**Comment by skaravad** [comment]
I did some quick test and the authentication appears to work, however, there are few security issues which I discovered. Will open a new bug
