### ISSUE TITLE
LDAP RBAC cont

### ISSUE THREAD

**Issue by eladeyal-intel** [rickbergfalk/sqlpad#861]
So the LDAP_FILTER env var can be used to allow LDAP users to auto-sign in and prevent others for auto-signin?

So if I want only users in "finance" dept to be able to log-in to sqlpad, I must use a complex filter.

Maybe we can improve this slightly by setting the "LDAP DEFAULT ROLE" also accept "denied". So in this case if the user matches the FILTER but none of the ROLE_FILTERs then she is denied altogether. This will make the FILTER simpler.

**Comment by rickbergfalk** [comment]
I think that's a good idea especially since the user filter and roles will overlap if that isn't the case. 

For default role I'm thinking of making the default an empty string, and having that also reject an authentication attempt if no role was matched? `denied` can also be used to make the config explicit if desired.

**Comment by eladeyal-intel** [comment]
Thanks @rickbergfalk 

Are roles assign every login or only on sign up? I think it's not documented

**Comment by rickbergfalk** [comment]
Oh good call - it isn't documented but roles will be updated if changed on every login.

If there's not a match on a role filter at all though, the role will be left as is. As I think about it this could be problematic, because you might want someone's account disabled if they no longer match a role filter.

The reason those logins are allowed is that you may want to have other accounts created manually that you want to be able to log in?

I'm open to adjusting the logic used here or adding config to alter behavior, just need some guidance :)

**Comment by eladeyal-intel** [comment]
How about this

![image](https://user-images.githubusercontent.com/20379005/97108016-4961f880-16d3-11eb-8825-aa9c66741bff.png)


 Most users created via LDAP will have access as long as they have the relevant role in LDAP. But as an admin I will be able to "elevate" user so that even if she leaves the role, she will still be an admin.

**Comment by rickbergfalk** [comment]
I'm not opposed to adding the flexibility proposed, but I'd want to think about how to model this in the db and what impact it might have.

For short term would something strict work? For example, say if RBAC via LDAP is used, it strictly uses the LDAP filters, and it is up to you to ensure your LDAP setup makes that work. And if an LDAP-based SQLPad user account no longer fits a LDAP role filter, they get disabled.

**Comment by eladeyal-intel** [comment]
yes

**Comment by rickbergfalk** [comment]
Been thinking about this and I think I've settled on an implementation that won't require too many changes places. 

My initial thought was to have additional role fields, like `user.ldap_role`, that would always be updated for users that log in via LDAP. The original `user.role` field would be set to `ldap` or something, indicating that `user.ldap_role` should be used. This gets messy difficult to work with because the simplicity is lost. Everywhere in the codebase that refers to role needs to check 2 places (or there needs to be some additional virtual field that is populated based on some logic and that used).

Instead it occurred to me that we can add a flag that is used to manage whether roles should sync on a user. This could be something like `hasRoleByAuth = true`. The simplicity of the role check remains and most user role code won't have to change.

In the UI, if you decide to change the role or uncheck that flag, you opt-in to managing that assignment.

The benefit to this too is that it isn't tied to LDAP - this could be utilized by OIDC or SAML if those have something similar down the road.

**Comment by rickbergfalk** [comment]
The checkbox will only show if LDAP and role filters are configured. Also updating the intro about navigating to signup if local auth is turned on, since it does not apply to LDAP-only setups.

![image](https://user-images.githubusercontent.com/303966/97221941-97daca00-179b-11eb-828d-23f6b4d9aba3.png)
